# -----------------------------------------------------
# 1. SECRET (Mots de passe DB)
# -----------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "keycloak"
  POSTGRES_DB: "keycloak"

---
# -----------------------------------------------------
# 2. PVC (Stockage Persistant)
# -----------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# -----------------------------------------------------
# 3. DEPLOYMENT (Postgres)
# -----------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: keycloak-db-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: keycloak-postgres-pvc

---
# -----------------------------------------------------
# 4. SERVICE (Interne uniquement)
# -----------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
spec:
  type: ClusterIP
  selector:
    app: keycloak-postgres
  ports:
    - port: 5432
      targetPort: 5432