apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-gateway-service
  labels:
    app: faculty-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty-gateway-service
  template:
    metadata:
      labels:
        app: faculty-gateway-service
    spec:
      containers:
        - name: faculty-gateway-service
          image: faculty_management-faculty-gateway-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: CONFIG_SERVICE_URL
              value: "http://faculty-config-service:9999"
            - name: DISCOVERY_SERVICE_URL
              value: "http://faculty-discovery-service:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-gateway-service
spec:
  type: LoadBalancer   # Pour accéder depuis l'extérieur
  selector:
    app: faculty-gateway-service
  ports:
    - port: 8888
      targetPort: 8888
